{
 "title": "Hyperdrive Dashboard for Constellation v0.1.0",
 "description": "This is a prototype dashboard for Constellation node operators, based on the Rocket Pool dashboard.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Hardware Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validator Stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Node Uptime",
   "type": "stat",
   "description": "A count of how long your Beacon Node has been running. If you don't restart it, this is about the same as your total system uptime.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"bn\"}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "description": "The temperature of your CPU (you can set this to Tctl or Tdie, whichever you prefer to monitor).\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. The Rocket Pool setup guide has more information on this process: see https://docs.rocketpool.net/guides/node/grafana.html for more information.",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}"
    }
   ]
  },
  {
   "title": "Reboot Needed?",
   "type": "stat",
   "description": "(Feature not ready yet)\n\nThis will turn red when your system needs to be rebooted because of security updates.",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Updates",
   "type": "stat",
   "description": "(Feature not ready yet)\n\nTracks any updates that are available for your OS or for Hyperdrive but haven't been applied yet. When one of these numbers is higher than 0, it means you should update your system or Hyperdrive accordingly.",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "OS" }
   ]
  },
  {
   "title": "Swap Space Usage",
   "type": "gauge",
   "description": "How much of your total swap space you're currently using. If you have swap space enabled, you want this to be as low as possible - otherwise, your system is running out of free RAM.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{job=\"node\"} - node_memory_SwapFree_bytes{job=\"node\"}) / node_memory_SwapTotal_bytes{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "stat",
   "description": "Tracks the activity of all of your validators on the Beacon Chain. This is a cumulative count; it starts at 0 when your node first starts up, and then continuously increments as it goes.",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vc_signed_attestations_total{job=\"cs_vc\", status=\"success\"}) OR # Lighthouse\nsum(vc_published_attestations_total{job=\"cs_vc\"}) OR # Lodestar\nsum(beacon_attestations_sent_total{job=\"cs_vc\"}) OR # Nimbus\nsum(validator_successful_attestations{job=\"cs_vc\"}) OR # Prysm\nvalidator_duties_performed_total{job=\"cs_vc\", type=\"attestation\", result=\"success\"} OR # Teku\non() vector(0)",
     "legendFormat": "Attestations"
    },
    {
     "expr": "sum(vc_signed_beacon_blocks_total{job=\"cs_vc\", status=\"success\"}) OR # Lighthouse\nsum(vc_block_published_total{job=\"cs_vc\"}) OR # Lodestar\nsum(beacon_blocks_sent_total{job=\"cs_vc\"}) OR # Nimbus\nsum(validator_successful_proposals{job=\"cs_vc\"}) OR # Prysm\nvalidator_duties_performed_total{job=\"cs_vc\", type=\"block\", result=\"success\"} OR # Teku\non() vector(0)",
     "legendFormat": "Proposals"
    }
   ]
  },
  {
   "title": "Validator Activity",
   "type": "timeseries",
   "description": "Tracks the activity of all of your validators on the Beacon Chain.",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(vc_signed_beacon_blocks_total{job=\"cs_vc\", status=\"success\"}[$__rate_interval])) OR # Lighthouse\nsum(rate(vc_block_published_total{job=\"cs_vc\"}[$__rate_interval])) OR # Lodestar\nsum(rate(beacon_blocks_sent_total{job=\"cs_vc\"}[$__rate_interval])) OR # Nimbus\nsum(rate(validator_successful_proposals{job=\"cs_vc\"}[$__rate_interval])) OR # Prysm\nrate(validator_duties_performed_total{job=\"cs_vc\", type=\"block\", result=\"success\"}[$__rate_interval]) OR # Teku\non() vector(0)) * 45",
     "legendFormat": "Proposal"
    },
    {
     "expr": "(sum(rate(vc_signed_attestations_total{job=\"cs_vc\", status=\"success\"}[$__rate_interval])) OR # Lighthouse\nsum(rate(vc_published_attestations_total{job=\"cs_vc\"}[$__rate_interval])) OR # Lodestar\nsum(rate(beacon_attestations_sent_total{job=\"cs_vc\"}[$__rate_interval])) OR # Nimbus\nsum(rate(validator_successful_attestations{job=\"cs_vc\"}[$__rate_interval])) OR # Prysm\nrate(validator_duties_performed_total{job=\"cs_vc\", type=\"attestation\", result=\"success\"}[$__rate_interval]) OR # Teku\non() vector(0)) * 45",
     "legendFormat": "Attestation"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "The CPU usage of your Execution Client and Beacon Node + Validator Client pair, as well as your system total (with respect to all cores on your CPU).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_cpu_procload{job=\"geth\"} / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))) OR # Geth\nirate(process_cpu_seconds_total{job=\"ec\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) OR # Besu, Nethermind\nirate(reth_process_cpu_seconds_total{job=\"ec\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) # Reth",
     "legendFormat": "EC"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"bn\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"vc\"}[$__rate_interval]))) or vector(0))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "(1 - avg (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "System Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "The amount of RAM that your Execution Client, Beacon Node and Validator Client combo, and your whole system are using.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_used{job=\"geth\"} OR # Geth\nprocess_resident_memory_bytes{job=\"ec\"} OR # Besu\nprocess_working_set_bytes{job=\"ec\"} OR # Nethermind\nreth_process_resident_memory_bytes{job=\"ec\"} # Reth",
     "legendFormat": "EC"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"bn\"}) + (sum(process_resident_memory_bytes{job=\"cs_vc\"}) or vector(0))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "System Total"
    }
   ]
  },
  {
   "title": "Upcoming Proposals",
   "type": "stat",
   "description": "The number of block proposals you have coming up in the next few minutes. If you were planning on taking your node down for maintenance, you should wait until after the proposals because they're worth a lot of ETH!",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sync Committees",
   "type": "stat",
   "description": "The number of [sync committees](https://blockdaemon.com/blog/ethereum-altair-hard-folk-light-clients-sync-committees/) that you're about to be a part of, and that you're currently a part of.\n\nIf you were planning on doing maintenance to your node, **you should wait until the sync committee is over**. Not only are they worth an **extremely** large amount of ETH, but if you miss attestations during a sync committee, you **lose an extremely large amount of ETH** instead!\n\nYou should be online as long as possible while you are in a sync committee.",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "Upcoming" }
   ]
  },
  {
   "title": "Attestation Accuracy",
   "type": "timeseries",
   "description": "This chart shows the overall performance of your total attestations on the Beacon Chain, broken down by the individual attestation components - correct head, correct source, and correct target. If any of these are below 100%, you lost some rewards for submitting a late, partially incorrect, or fully incorrect attestation. For a detailed explanation of each component, take a look at Ben Edgington's explainer: https://eth2book.info/bellatrix/annotated-spec/\n\nThis is updated once per epoch, once your Beacon Node can see how well your node did during the previous epoch.\n\nNOTE: **Lighthouse** and **Teku** currently do not provide source correctness information, only head and target.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(validator_monitor_prev_epoch_on_chain_target_attester_hit{job=\"bn\", validator=\"total\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_target_attester_hit{job=\"bn\", validator=\"total\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_target_attester_miss{job=\"bn\", validator=\"total\"}[$__rate_interval]))) OR # Lighthouse\n(irate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total{job=\"bn\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_target_attester_hit_total{job=\"bn\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total{job=\"bn\"}[$__rate_interval]))) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_target{job=\"cs_vc\"}) / count(validator_correctly_voted_target{job=\"cs_vc\"})) OR # Prysm\n(validator_performance_correct_target_count{job=\"bn\"} / validator_performance_expected_attestations{job=\"bn\"}) # Teku",
     "legendFormat": "Target"
    },
    {
     "expr": "irate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total{job=\"bn\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_source_attester_hit_total{job=\"eth2\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total{job=\"bn\"}[$__rate_interval])) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_source{job=\"cs_vc\"}) / count(validator_correctly_voted_source{job=\"cs_vc\"})) # Prysm",
     "legendFormat": "Source"
    },
    {
     "expr": "irate(validator_monitor_prev_epoch_on_chain_head_attester_hit{job=\"bn\", validator=\"total\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_head_attester_hit{job=\"bn\", validator=\"total\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_head_attester_miss{job=\"bn\", validator=\"total\"}[$__rate_interval])) OR # Lighthouse\nirate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total{job=\"bn\"}[$__rate_interval]) / (irate(validator_monitor_prev_epoch_on_chain_head_attester_hit_total{job=\"bn\"}[$__rate_interval]) + irate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total{job=\"bn\"}[$__rate_interval])) OR # Nimbus and Lodestar\n(sum(validator_correctly_voted_head{job=\"cs_vc\"}) / count(validator_correctly_voted_head{job=\"cs_vc\"})) OR # Prysm\n(validator_performance_correct_head_block_count{job=\"bn\"} / validator_performance_expected_attestations{job=\"bn\"}) # Teku",
     "legendFormat": "Head"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Tracks the amount of CPU consumption for the Execution Client, the Beacon Node, and the total system. 100% means all of your CPU core are being used at their full capacity. The orange line indicates how much CPU a single core can provide in your system.\n\n**Note:** The EC's usage is stacked *on top of* the BN+VC, so it shows the aggregated amount of EC + BN + VC.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(1 - avg by (instance) (irate(node_cpu_seconds_total{job=\"node\", mode=\"idle\"}[$__rate_interval]))) * 100",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(avg (irate(process_cpu_seconds_total{job=\"bn\"}[$__rate_interval]))) + (sum(avg (irate(process_cpu_seconds_total{job=\"cs_vc\"}[$__rate_interval]))) or vector(0))) * 100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "(system_cpu_procload{job=\"geth\"} / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))) OR # Geth\nirate(process_cpu_seconds_total{job=\"ec\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) OR # Besu, Nethermind\nirate(reth_process_cpu_seconds_total{job=\"ec\"}[$__rate_interval]) * 100 / scalar(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) # Reth",
     "legendFormat": "EC (Stacked)"
    },
    {
     "expr": "100 / (count (node_cpu_seconds_total{job=\"node\", mode=\"idle\"}))",
     "legendFormat": "Single Core Cap"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Tracks the total amount of RAM usage by the eth2 client and the entire system, versus how much is available.\n\n**Note:** The EC's usage is stacked *on top of* the BN+VC, so it shows the aggregated amount of EC + BN + VC.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"} - node_memory_MemAvailable_bytes{job=\"node\"}",
     "legendFormat": "Total Used"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"bn\"}) + (sum(process_resident_memory_bytes{job=\"cs_vc\"}) or vector(0))",
     "legendFormat": "BN+VC"
    },
    {
     "expr": "system_memory_used{job=\"geth\"} OR # Geth\nprocess_resident_memory_bytes{job=\"ec\"} OR # Besu\nprocess_working_set_bytes{job=\"ec\"} OR # Nethermind\nreth_process_resident_memory_bytes{job=\"ec\"} # Reth",
     "legendFormat": "EC (Stacked)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\"}",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Next Attestation",
   "type": "stat",
   "description": "This tells you when your next attestation duty will arrive. Use it to find an optimal time to take your clients down for maintenance so you're back up and running before it hits.\n\n- NOTE: **Lodestar** and **Teku** do not provide this information.",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((min(vc_attestation_duty_slot{job=\"cs_vc\"}) - scalar(beacon_head_slot{job=\"bn\"})) * 12) OR # Lighthouse\nmax(next_action_wait{job=\"bn\"} OR # Nimbus\n(min((validator_next_attestation_slot{job=\"cs_vc\"} - scalar(beacon_slot{job=\"bn\"})) > 0 - 1) * 12) OR # Prysm\non() vector(0))"
    }
   ]
  },
  {
   "title": "VC Keys Loaded",
   "type": "stat",
   "description": "How many validator keys are currently loaded by your Validator Client.",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vc_signers_count{job=\"cs_vc\"} OR # Lodestar\nvc_validators_total_count{job=\"cs_vc\"} OR # Lighthouse\nvalidators{job=\"cs_vc\"} OR # Nimbus \ncount(validator_statuses{job=\"cs_vc\"}) OR # Prysm\nvalidator_local_validator_count{job=\"cs_vc\"} # Teku",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectivity",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "EC Peers",
   "type": "gauge",
   "description": "How many peers your EC is currently connected to.",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peers{job=\"geth\"} OR # Geth\nethereum_peer_count{job=\"ec\"} OR # Nethermind, Besu\nreth_network_connected_peers{job=\"ec\"} # Reth"
    }
   ]
  },
  {
   "title": "BN Peers",
   "type": "gauge",
   "description": "How many peers your Beacon Node is currently connected to on the Beacon Chain.",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sync_peers_per_status{job=\"bn\", sync_status=~\"Synced|Advanced\"}) OR # Lighthouse\nlodestar_peers_sync_count{job=\"bn\"} OR # Lodestar\nnbc_peers{job=\"bn\"} OR # Nimbus\np2p_peer_count{job=\"bn\", state=\"Connected\"} OR # Prysm\nbeacon_peer_count{job=\"bn\"} # Teku"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "description": "How many peers Execution Client and Beacon Node are currently connected to for blockchain traffic.",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(sync_peers_per_status{job=\"bn\", sync_status=~\"Synced|Advanced\"}) OR # Lighthouse\nlodestar_peers_sync_count{job=\"bn\"} OR # Lodestar\nnbc_peers{job=\"bn\"} OR # Nimbus\np2p_peer_count{job=\"bn\", state=\"Connected\"} OR # Prysm\nbeacon_peer_count{job=\"bn\"} # Teku",
     "legendFormat": "BN"
    },
    {
     "expr": "p2p_peers{job=\"geth\"} OR # Geth\nethereum_peer_count{job=\"ec\"} OR # Nethermind, Besu\nreth_network_connected_peers{job=\"ec\"} # Reth",
     "legendFormat": "EC"
    }
   ]
  },
  {
   "title": "I/O Wait Time",
   "type": "timeseries",
   "description": "This tracks how long it takes between one of your processes trying to read from / write to your SSD, and when that operation is actually performed. Think of this like \"how long SSD reads and writes have to wait in a queue before completing\". The longer this time, the longer it takes for your node to perform its Beacon Chain duties.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "The disk space used by your primary (Operating System) hard drive. Change the `device` option in this query to be your machine's hard drive.\n\nCheck Rocket Pool's guide for more information: see https://docs.rocketpool.net/guides/node/grafana.html.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\"}",
     "legendFormat": "OS"
    },
    {
     "expr": "(node_filesystem_size_bytes{job=\"node\", device=\"\"} - node_filesystem_avail_bytes{job=\"node\", device=\"\"}) / node_filesystem_size_bytes{job=\"node\", device=\"\"}",
     "legendFormat": "Disk 2"
    }
   ]
  },
  {
   "title": "Disk Temp",
   "type": "stat",
   "description": "The temperature of your SSD.\n\nTo get the correct chip and sensor ID, you'll want to run `sensors` from the `lm-sensors` package. \n\nCheck Rocket Pool's guide for more information: see https://docs.rocketpool.net/guides/node/grafana.html.",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}",
     "legendFormat": "OS"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"node\", chip=\"\", sensor=\"\"}",
     "legendFormat": "Disk 2"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Chain Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SSD Latency",
   "type": "timeseries",
   "description": "The average read/write latency of your SSD. The lower it is, the faster your machine can process and respond to Beacon Chain activities like attesting. Change the `device` setting in the queries to be the SSD you want to track (typically the one with your chain data on it).\n\nCheck Rocket Pool's guide for more information: see https://docs.rocketpool.net/guides/node/grafana.html.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "OS Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "OS Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Disk 2 Write"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{job=\"node\", device=\"\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Disk 2 Read"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "description": "A chart showing the network I/O used by your main network adapter over time. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nCheck Rocket Pool's guide for more information: see https://docs.rocketpool.net/guides/node/grafana.html.",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\", device=\"\"}[$__rate_interval])",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Total Net I/O",
   "type": "stat",
   "description": "The total network I/O that has gone through your main network adapter. To make it work, change the `device` setting in the queries to match the name of the network adapter you want to track (you can use `ifconfig` to get a list of network adapters and find the right one). \n\nCheck Rocket Pool's guide for more information: see https://docs.rocketpool.net/guides/node/grafana.html.",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Tx"
    },
    {
     "expr": "node_network_receive_bytes_total{job=\"node\", device=\"\"}",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Beacon Balance",
   "type": "stat",
   "description": "The total ETH balance of all of your validators on the Beacon Chain. This is not your share of the balance; it includes rewards for Rocket Pool's rETH stakers and Constellation's xrETH stakers as well. It's more useful as a quick health check. As long as this number is going up, your validator is performing its duties.",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minipool Balance (EL)",
   "type": "stat",
   "description": "This is how much ETH is currently available for distribution in each of your minipool contracts (on the execution layer). \n\nConstellation handles minipool distribution automatically; you don't have to do this as a node operator. This is just shown purely for your own reference, and may be useful to track when rewards skimming occurs on the Beacon Chain.",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Wallet Balance",
   "type": "stat",
   "description": "The balance of your node wallet. Keep an eye on how much ETH you have; if it falls too low, your node won't be able to pay for gas during automatic transactions.",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{Token}}" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 26 },
   "targets": [
    {}
   ]
  }
 ]
}