package adapter_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/network"
	"github.com/docker/docker/client"
	internal_test "github.com/nodeset-org/hyperdrive/internal/test"
	"github.com/nodeset-org/hyperdrive/modules/config"
	"github.com/nodeset-org/hyperdrive/shared/adapter"
	"github.com/nodeset-org/hyperdrive/shared/utils/command"
)

var (
	// Adapter client
	ac *adapter.AdapterClient

	// Docker client
	docker *client.Client

	// Info for the example module
	modInfo *config.ModuleInfo
)

func TestMain(m *testing.M) {
	// Create a Docker client
	var err error
	docker, err = client.NewClientWithOpts(
		client.WithAPIVersionNegotiation(),
	)
	if err != nil {
		fail(fmt.Errorf("error creating Docker client: %w", err))
	}

	// Check if the adapter container is already created
	adapterID := getAdapterContainerID()
	if adapterID != "" {
		fail(fmt.Errorf("adapter container already exists - please remove it before running tests"))
	}

	// Initialize everything and get the adapter container info
	initializeArtifacts()
	adapterID = getAdapterContainerID()
	if adapterID == "" {
		fail(fmt.Errorf("adapter container not found"))
	}

	// Create the adapter client
	ac, err = adapter.NewAdapterClient(internal_test.AdapterContainerName, string(internal_test.TestKey))
	if err != nil {
		fail(fmt.Errorf("error creating adapter client: %w", err))
	}

	// Get the module config info
	modCfgMeta, err := ac.GetConfigMetadata(context.Background())
	if err != nil {
		fail(fmt.Errorf("error getting module config metadata: %w", err))
	}
	modInfo = &config.ModuleInfo{
		Descriptor:    internal_test.ExampleDescriptor,
		Configuration: modCfgMeta,
	}

	// Run the tests and clean up after
	code := m.Run()
	cleanup()
	os.Exit(code)
}

// Get the ID of the adapter container
func getAdapterContainerID() string {
	containerList, err := docker.ContainerList(context.Background(), container.ListOptions{
		All: true,
	})
	if err != nil {
		fail(fmt.Errorf("error inspecting adapter container: %w", err))
	}
	for _, container := range containerList {
		for _, name := range container.Names {
			if name == "/"+internal_test.AdapterContainerName {
				return container.ID
			}
		}
	}
	return ""
}

// Create the Docker container and initialize the adapter client
func initializeArtifacts() {
	// Make the dirs
	if err := os.MkdirAll(internal_test.LogDir, 0755); err != nil {
		fail(fmt.Errorf("error creating log dir: %w", err))
	}
	if err := os.MkdirAll(internal_test.CfgDir, 0755); err != nil {
		fail(fmt.Errorf("error creating config dir: %w", err))
	}
	if err := os.MkdirAll(filepath.Dir(internal_test.KeyPath), 0755); err != nil {
		fail(fmt.Errorf("error creating secrets dir: %w", err))
	}

	// Create the key file, or get the key if it already exists
	err := os.WriteFile(internal_test.KeyPath, []byte(internal_test.TestKey), 0644)
	if err != nil {
		fail(fmt.Errorf("error creating key file: %w", err))
	}

	// Create the docker network
	netCreateResponse, err := docker.NetworkCreate(context.Background(), internal_test.ProjectName+"_net", network.CreateOptions{
		Driver: "bridge",
		Scope:  "local",
		IPAM: &network.IPAM{
			Driver: "default",
			Config: []network.IPAMConfig{}, // Use an autogenerated IPAM config
		},
		Internal:   true,
		Attachable: false,
		Ingress:    false,
		ConfigOnly: false,
	})
	if err != nil {
		fail(fmt.Errorf("error creating network: %w", err))
	}
	if netCreateResponse.Warning != "" {
		fmt.Printf("warning creating network: %s\n", netCreateResponse.Warning)
	}

	// Create the container via the Docker CLI since it does stuff like pulling / tagging the image
	runCmd := fmt.Sprintf(
		"docker run --rm -d -e HD_PROJECT_NAME=%s -v %s:/hd/logs -v %s:/hd/config -v %s:/hd/secret --network %s_net --name %s %s", internal_test.ProjectName, internal_test.LogDir, internal_test.CfgDir, internal_test.KeyPath, internal_test.ProjectName, internal_test.AdapterContainerName, internal_test.AdapterTag)
	_, err = command.ReadOutput(runCmd)
	if err != nil {
		fail(fmt.Errorf("error running adapter container: %w", err))
	}
}

// Delete all of the config files from disk
func deleteConfigs() error {
	info, err := os.ReadDir(internal_test.CfgDir)
	if err != nil {
		return fmt.Errorf("error enumerating config directory: %w", err)
	}
	for _, entry := range info {
		err = os.Remove(filepath.Join(internal_test.CfgDir, entry.Name()))
		if err != nil {
			return fmt.Errorf("error removing config file [%s]: %w", entry.Name(), err)
		}
	}
	return nil
}

// Clean up the test environment
func cleanup() {
	// Stop the adapter container
	if docker != nil {
		timeout := 0
		_ = docker.ContainerStop(context.Background(), internal_test.AdapterContainerName, container.StopOptions{Timeout: &timeout})
		_ = docker.ContainerRemove(context.Background(), internal_test.AdapterContainerName, container.RemoveOptions{Force: true})
		_ = docker.NetworkRemove(context.Background(), internal_test.ProjectName+"_net")
	}

	// Remove the temp key file
	_ = os.Remove(internal_test.KeyPath)
}

// Clean up and exit with a failure
func fail(err error) {
	cleanup()
	fmt.Fprint(os.Stderr, err.Error())
	os.Exit(1)
}
